server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_user?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456              # ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.40.9:8848             # ${nacos.address}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60s #连接空闲超过N(s秒、ms毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      lettuce:
        pool:
          max-active: 8  #允许最大连接数
          max-idle: 8 #最大空闲连接数, 默认8
          min-idle: 0  #最小空闲连接数
          max-wait: 5s  #请求获取连接等待时间
  rabbitmq: #配置RabbitMQ的基本信息
    addresses: amqp://bite:bite@117.72.40.9:5672/bite
    listener:
      simple:
        acknowledge-mode: manual #配置⼿动确认
  mail:
    host: smtp.qq.com #需要在设置中开启 smtp
    username: 2230921218@qq.com #发件⼈的邮箱
    password: jffmjybejgcedjbj #邮箱的授权码, 并⾮个⼈密码
    default-encoding: UTF-8 #字符集编码, 默认 UTF-8
    properties:
      personal: "比特博客社区"
      mail:
        smtp:
          starttls:
            enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: user.log

---
##开发环境
#nacos:
#  address: 117.72.40.9:8848
#mysql:
#  password: 123456
#spring:
#  config:
#    activate:
#      on-profile: dev
#rabbitmq:
#  address: amqp://bite:bite@117.72.40.9:5672/blog
#---
##生产环境
#nacos:
#  address: 127.0.0.1:8848
#mysql:
#  password: Sq66+66=66
#spring:
#  config:
#    activate:
#      on-profile: prod
#rabbitmq:
#  address: amqp://bite:bite@127.0.0.1:5672/blog